package com.hospitality.mis.entity.identity;

/** Capabilities derived from the employee position, never from client-supplied grants. */
public enum Permission {
    EMPLOYEE_READ, EMPLOYEE_PROVISION, EMPLOYEE_PASSWORD_RESET,
    ROOM_READ, ROOM_WRITE, EQUIPMENT_READ, EQUIPMENT_WRITE,
    GUEST_READ, GUEST_WRITE,
    RESERVATION_READ, RESERVATION_CREATE, RESERVATION_WRITE, RESERVATION_CHECKOUT,
    RESERVATION_SERVICE_WRITE, INCIDENT_WRITE,
    BILLING_READ, BILLING_WRITE, PAYMENT_WRITE,
    SERVICE_READ, SERVICE_WRITE, INVENTORY_READ, INVENTORY_WRITE,
    MAINTENANCE_READ, MAINTENANCE_WRITE, FINANCE_READ, FINANCE_WRITE,
    APPROVAL_REQUEST, APPROVAL_APPROVE, AUDIT_READ
}
