CREATE TABLE LoaiPhong (
    MALOAIPHONG VARCHAR(10) PRIMARY KEY,
    TENLOAI VARCHAR(50) NOT NULL,
    GIA DECIMAL(12,2) NOT NULL,
    MOTA VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Phong (
    MAPHONG VARCHAR(10) PRIMARY KEY,
    MALOAIPHONG VARCHAR(10) NOT NULL,
    TINHTRANG ENUM(
        'SAN_SANG',
        'DANG_DON_DEP',
        'BAO_TRI',
        'DANG_O',
        'NGUNG_SU_DUNG',
        'DA_DAT',
        'DA_TRA',
        'DA_HUY'
    ) NOT NULL DEFAULT 'SAN_SANG',
    MOTA VARCHAR(255),
    CONSTRAINT fk_phong_loaiphong
        FOREIGN KEY (MALOAIPHONG)
        REFERENCES LoaiPhong(MALOAIPHONG)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE KhachHang (
    MAKH BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENKH VARCHAR(100) NOT NULL,
    DIACHI VARCHAR(255),
    SODIENTHOAI VARCHAR(15) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    CCCD VARCHAR(12) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE NhanVien (
    MANV VARCHAR(10) PRIMARY KEY,
    TENNV VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CHUCVU ENUM(
        'QUAN_LY',
        'PHUC_VU',
        'LE_TAN',
        'KE_TOAN',
        'DON_PHONG',
        'GIAM_SAT',
        'DAU_BEP',
        'THU_NGAN',
        'PHU_BEP',
        'NHAN_VIEN'
    ) NOT NULL,
    DIACHI VARCHAR(255),
    SODIENTHOAI VARCHAR(15) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DatPhong (
    MADP BIGINT AUTO_INCREMENT PRIMARY KEY,
    MAKH BIGINT NOT NULL,
    MANV VARCHAR(10) NOT NULL,
    NGAYDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GIACOC DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_datphong_khachhang
        FOREIGN KEY (MAKH)
        REFERENCES KhachHang(MAKH)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_datphong_nhanvien
        FOREIGN KEY (MANV)
        REFERENCES NhanVien(MANV)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ChiTietDatPhong (
    MADP BIGINT NOT NULL,
    MAPHONG VARCHAR(10) NOT NULL,
    NGAYNHAN DATETIME NOT NULL,
    NGAYTRA DATETIME NOT NULL,
    TINHTRANG ENUM(
        'SAN_SANG',
        'DANG_DON_DEP',
        'BAO_TRI',
        'DANG_O',
        'NGUNG_SU_DUNG',
        'DA_DAT',
        'DA_TRA',
        'DA_HUY'
    ) NOT NULL DEFAULT 'DA_DAT',
    SOLANCHUYENPHONG INT NOT NULL DEFAULT 0,
    PRIMARY KEY (MADP, MAPHONG),
    CONSTRAINT fk_ctdp_datphong
        FOREIGN KEY (MADP)
        REFERENCES DatPhong(MADP)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_ctdp_phong
        FOREIGN KEY (MAPHONG)
        REFERENCES Phong(MAPHONG)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DichVu (
    MADV VARCHAR(10) PRIMARY KEY,
    TENDICHVU VARCHAR(100) NOT NULL,
    GIADV DECIMAL(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ChiTietDichVu (
    MADP BIGINT NOT NULL,
    MADV VARCHAR(10) NOT NULL,
    NGAYSUDUNG DATE NOT NULL,
    SOLUONG INT NOT NULL DEFAULT 1,
    PRIMARY KEY (MADP, MADV, NGAYSUDUNG),
    CONSTRAINT fk_ctdv_datphong
        FOREIGN KEY (MADP)
        REFERENCES DatPhong(MADP)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_ctdv_dichvu
        FOREIGN KEY (MADV)
        REFERENCES DichVu(MADV)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE HoaDon (
    MAHOADON BIGINT AUTO_INCREMENT PRIMARY KEY,
    MADP BIGINT NOT NULL UNIQUE,
    NGAYXUATHD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TONGTIENPHONG DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TONGTIENDICHVU DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    GIAMGIA DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TIENCODADONG DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TONGTIENPHAITRA DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    PHUONGTHUCTHANHTOAN ENUM(
        'CHUYEN_KHOAN',
        'TIEN_MAT',
        'QUET_THE'
    ) DEFAULT NULL,
    TRANGTHAI ENUM(
        'DA_THANH_TOAN',
        'CHUA_THANH_TOAN',
        'DU_KIEN'
    ) NOT NULL DEFAULT 'CHUA_THANH_TOAN',
    CONSTRAINT fk_hoadon_datphong
        FOREIGN KEY (MADP)
        REFERENCES DatPhong(MADP)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BaoTri (
    MABT VARCHAR(10) PRIMARY KEY,
    MAPHONG VARCHAR(10) NOT NULL,
    LOAIBAOTRI VARCHAR(100) NOT NULL,
    NGAYBAOTRI DATE NOT NULL,
    TINHTRANGBTRI ENUM(
        'CHUA_XU_LY',
        'DANG_BAO_TRI',
        'DA_HOAN_THANH'
    ) NOT NULL DEFAULT 'CHUA_XU_LY',
    MOTA VARCHAR(255),
    CONSTRAINT fk_baotri_phong
        FOREIGN KEY (MAPHONG)
        REFERENCES Phong(MAPHONG)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ChuyenPhong (
    MACHUYENPHONG BIGINT AUTO_INCREMENT PRIMARY KEY,
    MADP BIGINT NOT NULL,
    MAPHONGCU VARCHAR(10) NOT NULL,
    MAPHONGMOI VARCHAR(10) NOT NULL,
    NGAYCHUYEN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LYDO VARCHAR(255),
    CONSTRAINT fk_chuyenphong_datphong
        FOREIGN KEY (MADP)
        REFERENCES DatPhong(MADP)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_chuyenphong_phongcu
        FOREIGN KEY (MAPHONGCU)
        REFERENCES Phong(MAPHONG)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_chuyenphong_phongmoi
        FOREIGN KEY (MAPHONGMOI)
        REFERENCES Phong(MAPHONG)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_datphong_khach ON DatPhong(MAKH);
CREATE INDEX idx_datphong_nhanvien ON DatPhong(MANV);

CREATE INDEX idx_chitietdatphong_phong ON ChiTietDatPhong(MAPHONG);
CREATE INDEX idx_chitietdatphong_ngay ON ChiTietDatPhong(NGAYNHAN, NGAYTRA);

CREATE INDEX idx_ctdv_madv ON ChiTietDichVu(MADV);

CREATE INDEX idx_baotri_maphong ON BaoTri(MAPHONG);
CREATE INDEX idx_chuyenphong_madp ON ChuyenPhong(MADP);
CREATE INDEX idx_chuyenphong_phongcu ON ChuyenPhong(MAPHONGCU);
CREATE INDEX idx_chuyenphong_phongmoi ON ChuyenPhong(MAPHONGMOI);